title: "Oracle PiDay on OCI with MDS"
description: "Oracle PiDay IOT to OCI with MySQL Database Service"
schemaVersion: 1.0.0
version: "20220308"
locale: "en"


variableGroups:
  - title: "General Configuration"
    visible: false
    variables:
      - tenancy_ocid
      - compartment_ocid
      - region
      - ssh_authorized_keys_path
      - ssh_private_key_path
      - private_key_path

  - title: Required Variables
    visible: true
    variables:
      - admin_username
      - admin_password
      - mds_instance_name
      - iot_instance_name

  - title: IoT Server
    visible: true
    variables:
     - use_mosquitto
     - mosquitto_username
     - mosquitto_password

  - title: Use HA for MDS
    visible: true
    variables:
      - deploy_mds_ha

  - title: Deploy HeatWave Cluster
    variables:
      - deploy_mds_heatwave
      - heatwave_cluster_size
    visible:
      and:
        - or:
          - eq:
            - mysql_shape
            - "MySQL.HeatWave.VM.Standard.E3"

  - title: Shapes
    visible: true
    variables:
      - node_shape
      - node_flex_shape_ocpus
      - node_flex_shape_memory
      - mysql_shape

  - title: Network
    visible: true
    variables:
      - vcn
      - vcn_cidr

  - title: Use Existing Intrastructure
    visible: true
    variables:
      - useExistingInfra
      - existing_vcn_ocid
      - existing_internet_gateway_ocid
      - existing_nat_gateway_ocid
      - existing_public_route_table_ocid
      - existing_private_route_table_ocid
      - existing_public_security_list_ocid
      - existing_public_security_list_http_ocid
      - existing_private_security_list_ocid
      - existing_public_subnet_ocid
      - existing_private_subnet_ocid
      - existing_mds_instance_ocid

variables:
  region:
    type: oci:identity:region:name
    visible: false
    required: true
    title: ${Messages.solutionsHub.genericVariables.region.title()}
    description: ${Messages.solutionsHub.genericVariables.region.description()}

  useExistingInfra:
    title: Use Existing Infrastructure Resources
    type: boolean
    default: false


  use_mosquitto:
    title: Deploy Open Source MQTT v5/v3.1.x Broker Mosquitto instead of MysQL Router
    type: boolean
    default: false

  node_shape:
    type: oci:core:instanceshape:name
    title: "Select a shape for the Zeppelin Compute Instance"
    dependsOn:
      compartmentId: compartment_ocid

  node_flex_shape_memory:
    type: number
    required: false
    minimum: 1
    maximum: 128
    multipleOf: 1
    default: 6
    title: "Flex Shape Memory (GB)"
    description: "Choose number GB for Flex Shape Memory."
    visible:
      and:
        - or:
          - eq:
            - node_shape
            - "VM.Standard.E3.Flex"
          - eq:
            - node_shape
            - "VM.Standard.E4.Flex"
          - eq:
            - node_shape
            - "VM.Standard.A1.Flex"
          - eq:
            - node_shape
            - "VM.Optimized3.Flex"
          - eq:
            - node_shape
            - "VM.Standard3.Flex"
          - eq:
            - node_shape
            - "VM.Standard4.Flex"


  node_flex_shape_ocpus:
    type: number
    required: false
    minimum: 1
    maximum: 128
    multipleOf: 1
    default: 1
    title: "Flex Shape OCPUs"
    description: "Choose number of OCPUs for Flex Shape."
    visible:
      and:
        - or:
          - eq:
            - node_shape
            - "VM.Standard.E3.Flex"
          - eq:
            - node_shape
            - "VM.Standard.E4.Flex"
          - eq:
            - node_shape
            - "VM.Standard.A1.Flex"
          - eq:
            - node_shape
            - "VM.Optimized3.Flex"
          - eq:
            - node_shape
            - "VM.Standard3.Flex"
          - eq:
            - node_shape
            - "VM.Standard4.Flex"


  existing_vcn_ocid:
    type: oci:core:vcn:id
    visible: ${useExistingInfra}
    title: VNC OCID
    description: OCID of existing VCN to use
    dependsOn:
      compartmentId: compartment_ocid
  existing_internet_gateway_ocid:
    type: string
    visible: ${useExistingInfra}
    title: Internet Gateway OCID
    description: OCID of existing Internet Gateway to use
  existing_nat_gateway_ocid:
    type: string
    visible: ${useExistingInfra}
    title: NAT Gateway OCID
    description: OCID of existing NAT Gateway to use
  existing_public_route_table_ocid:
    type: string
    visible: ${useExistingInfra}
    title: Public Routing Table OCID
    description: OCID of existing Public Routing Table to use
  existing_private_route_table_ocid:
    type: string
    visible: ${useExistingInfra}
    title: Private Routing Table OCID
    description: OCID of existing Private Routing Table to use
  existing_public_security_list_ocid:
    type: string
    visible: ${useExistingInfra}
    title: Public Security List OCID
    description: OCID of existing Public Security List (ssh access) to use
  existing_public_security_list_http_ocid:
    type: string
    visible: ${useExistingInfra}
    title: HTTP Public Security List OCID
    description: OCID of existing HTTP Public Security List to use
  existing_private_security_list_ocid:
    type: string
    visible: ${useExistingInfra}
    title: Private Security List OCID
    description: OCID of existing Private Security List allowing MySQL traffic to use
  existing_public_subnet_ocid:
    type: oci:core:subnet:id
    dependsOn:
      compartmentId: compartment_ocid
      vcnId: existing_vcn_ocid
    visible: ${useExistingInfra}
    title: Public Subnet OCID
    description: OCID of existing Public Subnet to use
  existing_private_subnet_ocid:
    type: oci:core:subnet:id
    dependsOn:
      compartmentId: compartment_ocid
      vcnId: existing_vcn_ocid
    visible: ${useExistingInfra}
    title: Private Subnet OCID
    description: OCID of existing Private Subnet to use
  existing_mds_instance_ocid:
    type: string
    visible: ${useExistingInfra}
    title: MDS instance OCID
    description: OCID of existing MySQL Instance to use

  vcn:
    type: string
    visible: false
    required: true
    title: ${Messages.solutionsHub.solutions.defaultVCN.variables.vcn_display_name.title()}
    description: ${Messages.solutionsHub.solutions.defaultVCN.variables.vcn_display_name.description()}

  vcn_cidr:
    type: string
    visible: false
    required: false
    pattern: "^(25[0-5]|2[0-4][0-9]|1[0-9][0-9]|[1-9]?[0-9]).(25[0-5]|2[0-4][0-9]|1[0-9][0-9]|[1-9]?[0-9]).(25[0-5]|2[0-4][0-9]|1[0-9][0-9]|[1-9]?[0-9]).(25[0-5]|2[0-4][0-9]|1[0-9][0-9]|[1-9]?[0-9])\\/(3[0-2]|[1-2]?[0-9])$"
    title: ${Messages.solutionsHub.solutions.defaultVCN.variables.vcn_cidr.title()}
    description: ${Messages.solutionsHub.solutions.defaultVCN.variables.vcn_cidr.description()}

  compartment_ocid:
    type: oci:identity:compartment:id
    required: true
    title: Compartment
    description: Compartment where you want to create the solution resources

  admin_username:
    type: string
    required: true
    title: MDS Admin Username
    description: MySQL Database Service's admin username
    minLength: 1
    maxLength: 14
    pattern: "^[a-zA-Z][a-zA-Z0-9]+$"

  admin_password:
    type: password
    required: true
    title: MDS Admin User's Password
    description: Password for MySQL Database Service's admin user
    pattern: "^(?=.*[0-9])(?=.*[a-z])(?=.*[A-Z])(?=.*[!@#$%^&*()_+\\-=\\[\\]{};':\\\"\\\\|,.<>\\/?]).{8,32}$"

  deploy_mds_ha:
    title: Deploy High Availability for MDS
    type: boolean
    default: false

  deploy_mds_heatwave:
    title: Deploy HeatWave Cluster
    type: boolean
    default: false

  heatwave_cluster_size:
    title: Size of HeatWave Cluster
    type: integer
    default: 2
    visible: ${deploy_mds_heatwave}

  mosquitto_password:
    type: password
    required: true
    title: Mosquitto User Password
    description: Password for Mosquitto User
    pattern: "^(?=.*[0-9])(?=.*[a-z])(?=.*[A-Z])(?=.*[@#$%^&*()_+\\-=\\[\\]{};':\\\"\\\\|,.<>\\/?]).{8,32}$"
    visible: ${use_mosquitto}

  mds_instance_name:
    type: string
    required: true
    title: MySQL Database Service Instance's name

  iot_instance_name:
    type: string
    required: true
    title: IoT Compute Instance's name

  mosquitto_username:
    type: string
    required: true
    title: Mosquitto Username
    description: Username for Mosquitto
    minLength: 2
    maxLength: 14
    pattern: "^[a-zA-Z][a-zA-Z0-9]+$"
    visible: ${use_mosquitto}

  user_ocid:
    visible: false
  fingerprint:
    visible: false
  dns_label:
    visible: false
  node_image_id:
    visible: false
  label_prefix:
    visible: false
